"use client";
import {useState} from 'react';
import Link from 'next/link';
import catalogue from '@/generated/catalogue.json';
const assessment=catalogue.assessment;
import {useLearning} from '@/lib/learning-store';
export default function Skills(){
 const state=useLearning(),[answers,setAnswers]=useState<Record<string,number>>({}),[checked,setChecked]=useState(false);
 const [phase,setPhase]=useState(catalogue.phases[0].slug);
 return <main className="page-shell"><h1 className="page-title">Bản đồ kiến thức & hồ sơ năng lực</h1><p>Kiểm tra đầu vào chỉ gợi ý điểm bắt đầu; không cấp kết quả đạt kiểm thử.</p><section className="learning-card"><h2>Kiểm tra đầu vào</h2>{assessment.map(q=><fieldset key={q.id}><legend>{q.question}</legend>{q.choices.map((choice,i)=><label key={choice}><input type="radio" name={q.id} checked={answers[q.id]===i} onChange={()=>{setAnswers({...answers,[q.id]:i});setChecked(false);}}/> {choice}</label>)}{checked&&<p>{answers[q.id]===q.answer?'Đúng. ':'Cần ôn. '}{q.explanation} <Link href={`/docs/${catalogue.exercises.find(e=>e.id===q.id)!.phase}#${q.id}`}>Học {q.id}</Link></p>}</fieldset>)}<button disabled={Object.keys(answers).length<assessment.length} onClick={()=>setChecked(true)}>Xem giải thích và bài nên ôn</button></section><section className="learning-card"><h2>Quan hệ kiến thức tiên quyết</h2><label>Chủ đề<select value={phase} onChange={e=>setPhase(e.target.value)}>{catalogue.phases.map(p=><option key={p.slug} value={p.slug}>{p.title}</option>)}</select></label>{catalogue.exercises.filter(e=>e.phase===phase).map(e=><p key={e.id}>{e.prerequisites.length?e.prerequisites.join(' + '):'Bắt đầu'} → <Link href={`/docs/${e.phase}#${e.id}`}>{e.id} — {e.title}</Link></p>)}</section><section className="learning-card"><h2>Hồ sơ hiện tại</h2><p>Tự đánh dấu: {Object.values(state.entries).filter(e=>e.status==='self_completed').length} bài · Đạt kiểm thử: {state.verified.length} bài · Cần ôn: {Object.values(state.entries).filter(e=>e.status==='needs_review').length} bài.</p><p>Các bài đã dùng gợi ý: {Object.entries(state.entries).filter(([,e])=>e.hint_level>0).map(([id,e])=>`${id} (cấp ${e.hint_level})`).join(', ')||'Chưa có'}.</p><p>Lịch sử nộp và chẩn đoán nằm ở từng bài. Bằng chứng commit chưa được tích hợp/xác minh tự động; không dùng số commit làm điểm kiểm thử.</p><Link href="/lab">Mở bàn thử nghiệm RAG và luồng request</Link></section></main>;
}
