import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8').replaceAll('\r\n','\n');
const catalogue = JSON.parse(read('learning/catalogue.json'));
const hints = JSON.parse(read('learning/hints.json'));
const sessions = JSON.parse(read('learning/sessions.json'));
const assessment = JSON.parse(read('learning/assessment.json'));
function section(source, id) {
  const escaped = id.replaceAll('.', '\\.');
  const heading = new RegExp(`^#{2,3} ${escaped}(?:\\s|[—.:])[^\\n]*`, 'm').exec(source);
  if (heading) {
    const rest = source.slice(heading.index + heading[0].length);
    return rest.slice(0, rest.search(/^#{1,3} /m) < 0 ? rest.length : rest.search(/^#{1,3} /m)).trim();
  }
  const row = source.split('\n').find(line => new RegExp(`^\\| ${escaped}(?: |\\|)`).test(line));
  if(row) {
    const header=source.split('\n').find(line=>line.startsWith('| '));
    const cells=line=>line.split('|').slice(1,-1).map(v=>v.trim());
    const labels=cells(header),values=cells(row);
    return values.map((value,i)=>`- **${labels[i]||'Chi tiết'}:** ${value}`).join('\n');
  }
  return source;
}
const exercises = Object.entries(catalogue.exercises).map(([id, entry]) => {
  if (!catalogue.phases.some(p => p.slug === entry.phase)) throw Error(`Unknown phase: ${id}`);
  for (const pre of entry.prerequisites) if (!catalogue.exercises[pre]) throw Error(`Unknown prerequisite: ${pre}`);
  const markdown = section(read(entry.reading), id);
  const solution = entry.solution ? section(read(entry.solution), id) : 'Bài thực hành thủ công: đối chiếu tiêu chí và lưu bằng chứng; không tự cấp đạt kiểm thử.';
  return { id, ...entry, markdown, solution, hints: hints[id] || [] };
});
for (const session of sessions) for (const id of session.exercise_ids || []) if (!catalogue.exercises[id]) throw Error(`Unknown session exercise ${id}`);
const visited=new Set(),visiting=new Set();
function visit(id){if(visiting.has(id))throw Error(`Prerequisite cycle: ${id}`);if(visited.has(id))return;visiting.add(id);catalogue.exercises[id].prerequisites.forEach(visit);visiting.delete(id);visited.add(id);}
Object.keys(catalogue.exercises).forEach(visit);
for(const e of exercises)if(e.hints.length!==3)throw Error(`Missing three hints: ${e.id}`);
function browserLinks(text, file) {
 return text.replace(/\]\(([^)]+)\)/g,(all,target)=>{
  if(/^(https?:|mailto:|#)/.test(target))return all;
  const resolved=path.posix.normalize(path.posix.join(path.posix.dirname(file),target));
  return ']('+ 'https://github.com/VanDung279206/JavaBackend_AI_RoadMap/blob/RoadMap_v3/' +resolved+')';
 });
}
for(const e of exercises){e.markdown=browserLinks(e.markdown,e.reading);e.solution=browserLinks(e.solution,e.solution?catalogue.exercises[e.id].solution||e.reading:e.reading);}
const output = JSON.stringify({ phases: catalogue.phases, tags: catalogue.tags, exercises, sessions, assessment }, null, 2) + '\n';
const target = path.join(root, 'website/src/generated/catalogue.json');
const sql = '-- Generated by scripts/build_catalogue.mjs; apply after V4, before V5.\nINSERT INTO public.learning_phases(slug,title) VALUES\n' + catalogue.phases.map(p=>`('${p.slug}', '${p.title.replaceAll("'", "''")}')`).join(',\n') + '\nON CONFLICT(slug) DO UPDATE SET title=EXCLUDED.title;\nINSERT INTO public.exercise_catalogue (phase, exercise_id, title) VALUES\n' + exercises.map(e => `('${e.phase.replaceAll("'", "''")}', '${e.id}', '${e.title.replaceAll("'", "''")}')`).join(',\n') + '\nON CONFLICT (phase, exercise_id) DO UPDATE SET title = EXCLUDED.title;\n';
const outputs = [[target, output], [path.join(root, 'database/catalogue_seed.sql'), sql]];
const tableCell = value => String(value).replaceAll('|', '\\|');
const sourceLink = (label, file) => `[${label}](${path.posix.relative('docs',file)})`;
const mapIntro = '# Bản đồ bài tập và kiểm tra\n\n<!-- Generated by scripts/build_catalogue.mjs; edit learning/catalogue.json instead. -->\n\nNguồn duy nhất: [catalogue](../learning/catalogue.json). Các lệnh chạy từ gốc repo. Lệnh dùng `py` trên Windows; máy khác thay bằng Python 3 đã cài. Bản tham chiếu không cấp tiến độ người học.\n\nVới Spring, tạo bản tự làm **một lần** bằng `new_spring_lab.py`; script từ chối ghi đè thư mục cũ. Các lần sau chỉ chạy lệnh kiểm tra trên bản đó. P3.1–P3.4 phụ thuộc tăng dần; chạy test theo bài rồi toàn bộ test khi hết phase. P4.3/P4.4 cần bằng chứng Docker/CI thực, Maven PASS không xác nhận hai bài này.\n\n| ID / bài | Phase | Nguồn tự làm / kiểm tra | Lệnh và phạm vi | Đề / đối chiếu |\n| --- | --- | --- | --- | --- |\n';
const mapRows = exercises.map(e => {
 const source = catalogue.exercises[e.id];
 const links = sourceLink('Đề',e.reading) + (source.solution ? ' · ' + sourceLink('Đối chiếu',source.solution) : ' · Tự kiểm bằng bằng chứng');
 const commands = e.check.command.split('\n').map(line=>'`'+tableCell(line)+'`').join('<br>');
 return `| ${tableCell(e.id+' — '+e.title)} | ${e.phase} | \`${tableCell(e.check.file)}\` | ${commands}<br>${tableCell(e.check.note)} | ${links} |`;
}).join('\n');
outputs.push([path.join(root,'docs/EXERCISE_MAP.md'),mapIntro+mapRows+'\n\nBài có check thủ công không được tự cấp verified PASS. Xem [VALIDATION](../VALIDATION.md) cho kết quả thực chạy và các phần BLOCKED.\n']);
for(const phase of catalogue.phases.filter(p=>/^0[1-6]_/.test(p.slug)))for(const name of ['EXERCISES.md','SOLUTIONS.md']){
 const source='phases/'+phase.slug+'/'+name;
 outputs.push([path.join(root,'website/public/content',phase.slug,name),browserLinks(read(source),source)]);
}
for (const [file, content] of outputs) {
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8').replaceAll('\r\n','\n') !== content) throw Error(`Stale generated file: ${file}`);
  } else { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content); }
}
console.log(`PASS catalogue: ${exercises.length} exercises, ${sessions.length} sessions`);
